language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt -t lib"
# command to run tests
script: echo "Tested!"

deploy:
    provider: gae
    skip_cleanup: true
    keyfile: gcp.json
    project: alexwiss-website
    default: true